### ISSUE TITLE
Dependabot alerts are not triggering

### ISSUE THREAD

**Issue by niksy** [sublimelsp/LSP-twiggy#2]
It seems like dependabot alerts are not triggering. Latest language server version is 0.17.0 and it’s been released 2 days ago.

**Comment by rchl** [comment]
Because it's configured to run on daily interval which means weekdays only, see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval

I've triggered it manually now.
